#!/usr/bin/env bash
# Azhi Flow team install: PostgreSQL 16 + pgvector, Temporal and the Azhi server, from a clone of
# this repository to a healthy server and an owner token. Re-running it is safe: secrets in
# deploy/.env are generated once and kept, and compose only recreates what changed.
#
#   deploy/install.sh            # install or upgrade
#   AZHI_PORT=8400 deploy/install.sh
#   AZHI_NODE_IMAGE=mirror.gcr.io/library/node:22-bookworm-slim deploy/install.sh   # Docker Hub rate limits
#
# Workers are installed separately on Linux hosts (see docs/install.md).
set -euo pipefail
cd "$(dirname "$0")"

need() { command -v "$1" >/dev/null || { echo "install.sh: $1 is required ($2)" >&2; exit 1; }; }
need docker "https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || { echo "install.sh: the Docker Compose plugin is required" >&2; exit 1; }
need openssl "used to generate the server secret"

if [[ ! -f .env ]]; then
  umask 077
  cat > .env <<ENV
# Generated by deploy/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Keep this file private.
AZHI_SECRET_KEY=$(openssl rand -hex 32)
AZHI_PG_PASSWORD=$(openssl rand -hex 16)
ENV
  echo "wrote deploy/.env with a new server secret and database password"
fi

project=${AZHI_COMPOSE_PROJECT:-azhi}
compose=(docker compose -p "$project" -f docker-compose.yml --env-file .env --profile server)
t0=$(date +%s)
"${compose[@]}" pull --quiet --ignore-buildable --ignore-pull-failures
t1=$(date +%s)
# AZHI_SKIP_BUILD=1 uses an azhi-flow/server image that is already present (built or loaded).
[[ "${AZHI_SKIP_BUILD:-}" == 1 ]] || "${compose[@]}" build --quiet
t2=$(date +%s)
"${compose[@]}" up -d --wait --no-build
t3=$(date +%s)

token=$("${compose[@]}" exec -T azhi sh -c 'cat /data/local-token 2>/dev/null' || true)
port=${AZHI_PORT:-7400}
echo
echo "Azhi Flow is up at http://localhost:${port} (pull $((t1 - t0))s, build $((t2 - t1))s, start $((t3 - t2))s, total $((t3 - t0))s)"
if [[ -n "$token" ]]; then
  echo
  echo "Owner token (local auth mode). Save it, then on your machine:"
  echo "  azhi login --url http://localhost:${port} --token ${token}"
fi
echo
echo "Next: start a worker on a Linux host (docs/install.md), then 'azhi doctor'."
